apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: a073072.azurecr.io/order
          ports:
            - containerPort: 8080
